version: "3.9"
services:
  keycloak:
    image: "quay.io/keycloak/keycloak:21.1.1"
    command:
      - start-dev
      - --health-enabled=true
      - --import-realm
    volumes:
      - keycloak:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
volumes:
  keycloak:
